name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.1.0
    - name: Install dependencies
      run: yarn
    - name: Check linting
      run: yarn lint
    - name: Check tests
      run: yarn test
      env:
        CI: true
